# Generated by Django 4.2 on 2023-04-05 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dzial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzial', models.CharField(max_length=20, unique=True)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_pracownika', models.DecimalField(decimal_places=0, max_digits=4, unique=True)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=40)),
                ('zatrudniony', models.BooleanField(default=True)),
                ('dzial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szkolenia.dzial')),
            ],
        ),
        migrations.CreateModel(
            name='Szkolacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szkolenia.dzial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='szkolacy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Szkolenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_szkolenia', models.DateField(verbose_name='data szkolenia')),
                ('czas_szkolenia', models.TimeField(verbose_name='czas szkolenia')),
                ('temat', models.CharField(max_length=250)),
                ('opis', models.CharField(max_length=2500)),
                ('data_dodania', models.DateField(blank=True, null=True, verbose_name='data dodania')),
                ('szkolacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szkolenia.szkolacy')),
            ],
        ),
        migrations.CreateModel(
            name='Szkolenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szkolenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szkolenia.szkolenia')),
                ('uczestnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szkolenia.pracownik')),
            ],
        ),
        migrations.CreateModel(
            name='Lider_Dzial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szkolenia.dzial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
