# Generated by Django 4.2 on 2023-04-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szkolenia', '0004_remove_autor_aktywny_remove_autor_nadzor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='szkolacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='szkolenia',
            name='szkolacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szkolenia.pracownik'),
        ),
    ]
